name: trophyapp
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^2.1.0
  #do not enter version of flutter_svg package
  #  flutter_svg:
  flutter_svg: ^0.22.0
  #flutter_secure_storage: ^3.3.5
  dio: ^4.0.0
  path: ^1.7.0
  http: ^0.13.3
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  share: ^2.0.4
  image_picker: ^0.8.2
  flutter_exif_rotation: ^0.4.1
  draggable_scrollbar: ^0.1.0
  url_launcher: ^6.0.9
  flutter_archive: ^4.0.1
  smooth_page_indicator: ^0.2.0
  video_player: ^2.1.12
  qr_mobile_vision: ^3.0.0
  flutter_html: ^2.1.0
  html: ^0.15.0
  swipedetector: ^1.2.0
 

  flutter_secure_storage: ^4.2.1
  pie_chart:
    git:
      url: https://github.com/aleksey-smx/pie_chart.git
      ref: master
  flutter_cube:
    git:
      url: https://github.com/zesage/flutter_cube.git
      ref: master

  
 
  
  typed_data: ^1.3.0
  flutter_facebook_auth: ^3.5.1
  flutter_local_notifications: ^6.1.0
  flutter_launcher_icons: ^0.9.1


  
#dependency_overrides:
# qr_mobile_vision:
#  git:
##  ref: "use-mlkit"

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.8.0
  dart_code_metrics: ^4.1.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
